version: "3.5"
name: "nova"
services:
  db:
    image: "postgres"
    restart: always
    container_name: nova-db
    environment:
      POSTGRES_USER: "wafiq"
      POSTGRES_DB: "nova"
      POSTGRES_PASSWORD: wafiq123
    volumes:
      - database-data:/var/lib/postgresql-data/
    ports:
      - 8010:5432

volumes:
  database-data: