version: "3.5"
name: "nova"
services:
  db:
    image: "postgres:latest"
    restart: always
    container_name: nova-db
    environment:
      POSTGRES_USER: "wafiq"
      POSTGRES_DB: "nova"
      POSTGRES_PASSWORD: wafiq123
    volumes:
      - database-data:/var/lib/postgresql-data/
    ports:
      - 8010:5432
  redis:
    image: redis/redis-stack
    restart: unless-stopped
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redisdata:/data 

volumes:
  database-data:
  redisdata: